package com;
// Generated 5 f�vr. 2023, 22:53:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "myregister")
public class Facture implements java.io.Serializable {

	private Integer idFacture;
	private Integer idPayement;
	private int idLivraison;
	private int idReservation;
	private Float amende;
	private Float montantAnvance;
	private Float montantTotal;

	public Facture() {
	}

	public Facture(int idLivraison, int idReservation) {
		this.idLivraison = idLivraison;
		this.idReservation = idReservation;
	}

	public Facture(Integer idPayement, int idLivraison, int idReservation, Float amende, Float montantAnvance,
			Float montantTotal) {
		this.idPayement = idPayement;
		this.idLivraison = idLivraison;
		this.idReservation = idReservation;
		this.amende = amende;
		this.montantAnvance = montantAnvance;
		this.montantTotal = montantTotal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_FACTURE_", unique = true, nullable = false)
	public Integer getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(Integer idFacture) {
		this.idFacture = idFacture;
	}

	@Column(name = "ID_PAYEMENT")
	public Integer getIdPayement() {
		return this.idPayement;
	}

	public void setIdPayement(Integer idPayement) {
		this.idPayement = idPayement;
	}

	@Column(name = "ID_LIVRAISON", nullable = false)
	public int getIdLivraison() {
		return this.idLivraison;
	}

	public void setIdLivraison(int idLivraison) {
		this.idLivraison = idLivraison;
	}

	@Column(name = "ID_RESERVATION", nullable = false)
	public int getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(int idReservation) {
		this.idReservation = idReservation;
	}

	@Column(name = "AMENDE", precision = 8)
	public Float getAmende() {
		return this.amende;
	}

	public void setAmende(Float amende) {
		this.amende = amende;
	}

	@Column(name = "MONTANT_ANVANCE", precision = 8)
	public Float getMontantAnvance() {
		return this.montantAnvance;
	}

	public void setMontantAnvance(Float montantAnvance) {
		this.montantAnvance = montantAnvance;
	}

	@Column(name = "MONTANT_TOTAL", precision = 8)
	public Float getMontantTotal() {
		return this.montantTotal;
	}

	public void setMontantTotal(Float montantTotal) {
		this.montantTotal = montantTotal;
	}

}
