package com;
// Generated 5 f�vr. 2023, 22:53:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Livraison generated by hbm2java
 */
@Entity
@Table(name = "livraison", catalog = "myregister")
public class Livraison implements java.io.Serializable {

	private Integer idLivraison;
	private Date dateLivraison;
	private String lieuLivraison;
	private Boolean livrer;

	public Livraison() {
	}

	public Livraison(Date dateLivraison, String lieuLivraison, Boolean livrer) {
		this.dateLivraison = dateLivraison;
		this.lieuLivraison = lieuLivraison;
		this.livrer = livrer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LIVRAISON", unique = true, nullable = false)
	public Integer getIdLivraison() {
		return this.idLivraison;
	}

	public void setIdLivraison(Integer idLivraison) {
		this.idLivraison = idLivraison;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_LIVRAISON", length = 19)
	public Date getDateLivraison() {
		return this.dateLivraison;
	}

	public void setDateLivraison(Date dateLivraison) {
		this.dateLivraison = dateLivraison;
	}

	@Column(name = "LIEU_LIVRAISON", length = 30)
	public String getLieuLivraison() {
		return this.lieuLivraison;
	}

	public void setLieuLivraison(String lieuLivraison) {
		this.lieuLivraison = lieuLivraison;
	}

	@Column(name = "LIVRER")
	public Boolean getLivrer() {
		return this.livrer;
	}

	public void setLivrer(Boolean livrer) {
		this.livrer = livrer;
	}

}
