package com;
// Generated 5 f�vr. 2023, 22:53:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paiyement generated by hbm2java
 */
@Entity
@Table(name = "paiyement", catalog = "myregister")
public class Paiyement implements java.io.Serializable {

	private Integer idPayement;
	private Float montantAPayer;
	private Float avance;
	private Float balance;
	private Date dateAvance;
	private Date dateFinPayement;

	public Paiyement() {
	}

	public Paiyement(Float montantAPayer, Float avance, Float balance, Date dateAvance, Date dateFinPayement) {
		this.montantAPayer = montantAPayer;
		this.avance = avance;
		this.balance = balance;
		this.dateAvance = dateAvance;
		this.dateFinPayement = dateFinPayement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PAYEMENT", unique = true, nullable = false)
	public Integer getIdPayement() {
		return this.idPayement;
	}

	public void setIdPayement(Integer idPayement) {
		this.idPayement = idPayement;
	}

	@Column(name = "MONTANT_A_PAYER", precision = 8)
	public Float getMontantAPayer() {
		return this.montantAPayer;
	}

	public void setMontantAPayer(Float montantAPayer) {
		this.montantAPayer = montantAPayer;
	}

	@Column(name = "AVANCE", precision = 8)
	public Float getAvance() {
		return this.avance;
	}

	public void setAvance(Float avance) {
		this.avance = avance;
	}

	@Column(name = "BALANCE", precision = 8)
	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_AVANCE", length = 19)
	public Date getDateAvance() {
		return this.dateAvance;
	}

	public void setDateAvance(Date dateAvance) {
		this.dateAvance = dateAvance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_FIN_PAYEMENT", length = 19)
	public Date getDateFinPayement() {
		return this.dateFinPayement;
	}

	public void setDateFinPayement(Date dateFinPayement) {
		this.dateFinPayement = dateFinPayement;
	}

}
