package com;
// Generated 5 f�vr. 2023, 22:53:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RetourMateriel generated by hbm2java
 */
@Entity
@Table(name = "retour_materiel", catalog = "myregister")
public class RetourMateriel implements java.io.Serializable {

	private Integer idRetour;
	private Integer idLivraison;
	private Date dateRetour;
	private String etatMateriel;

	public RetourMateriel() {
	}

	public RetourMateriel(Integer idLivraison, Date dateRetour, String etatMateriel) {
		this.idLivraison = idLivraison;
		this.dateRetour = dateRetour;
		this.etatMateriel = etatMateriel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_RETOUR", unique = true, nullable = false)
	public Integer getIdRetour() {
		return this.idRetour;
	}

	public void setIdRetour(Integer idRetour) {
		this.idRetour = idRetour;
	}

	@Column(name = "ID_LIVRAISON")
	public Integer getIdLivraison() {
		return this.idLivraison;
	}

	public void setIdLivraison(Integer idLivraison) {
		this.idLivraison = idLivraison;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_RETOUR", length = 19)
	public Date getDateRetour() {
		return this.dateRetour;
	}

	public void setDateRetour(Date dateRetour) {
		this.dateRetour = dateRetour;
	}

	@Column(name = "ETAT_MATERIEL", length = 20)
	public String getEtatMateriel() {
		return this.etatMateriel;
	}

	public void setEtatMateriel(String etatMateriel) {
		this.etatMateriel = etatMateriel;
	}

}
